# Generated by Django 5.0.2 on 2024-07-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Sneakers.brand'),
        ),
    ]
